### PR TITLE
[WIP] Add new designs

### PR DESCRIPTION
**Pull request by maya**
This is the new homepage design. 

TODOs:
- [ ] verify translations with @arantxarecio 

This is what it looks like:

Desktop:

p2a6pflzzrlgui2edaqcragqiaaaqiecbagqiaaaqiecbagqiaaaqiecbagqiaaaqieeiqqg7lzhlpipqdl1zybagqiecbagaabagqiecbagaabagqiecbagaabagqiecbagecegjbnnpdqagqiecbagaabagqiecbagaabagqiecbagaabagqiecbagacbprqqstndpruzaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqiea

Mobile:

pebx4zimazqsebfgayibaaecbagqiecaqklaayi4nf iknu2ngabagqiecbageaaaseiqbovqiaaaqiecbagqobiashisg1resbagaabagqieaggieqeakiscbagqiaaaqiecbwpieqcqw0tagqiecbagaabagee7gkr397lelex3te0aaaaaelftksuqmcc

Spanish:

whuytcg0ahjdgaaaabjru5erkjggg

### CODE REVIEW

**Comment by rogeruiz** [comment]
Awesome! @maya I think this PR should remain open for as long as we need to hold off on the deployment of v1 to production. Because once this PR is merge in, it's going to have all the changes clobber the v1 site.

Could you make new PRs associated with updates to v2 on a new branch that gets merged into `new-designs`. I can start with one which will allow `new-designs` to deploy to its own staging app on ☁️.gov.

**Comment by maya** [comment]
@rogeruiz yes, I can branch off of `new-designs` branch for all the further new designs work and open PRs against it.

**Comment by ericadeahl** [comment]
Hey @maya this is looking great. Just wanted to request a few very small changes:

- On desktop, increase the size of the ballot box so the bottom of the image bottom aligns with the bottom of the “Learn how to register” button.

- On mobile, center align the headline.

- On mobile, add padding between the “Find your polling place” link and the ballot box. It looks like it could also use a little extra space under the “Learn how to register” button, though that could just be an optical thing.

**Comment by maya** [comment]
@ericadeahl I made those updates which you can see on https://vote-gov-new-designs.apps.cloud.gov/

For the ballot box, I noticed the designs the ballot ends around mid-button and starts slightly below "Register to vote" heading so let me know if you'd like to match those proportions. (I grabbed the px values from Sketch initially which is why it may have been too small). For now, it goes to the end of the button.

I increased the padding on mobile. Let me know if that works or if you'd like any other adjustments.

**Comment by ericadeahl** [comment]
@maya 👍 Looks good, thank you!

**Comment by rogeruiz** [comment]
Taken from #87 written by @maya 

Adds new page layouts. 

**TODOs**:

- [ ] figure out where these layouts should go/live (right now they're in a catch-all `layouts/register/new-pages/`)
- [ ] generate the pages from content

For reference, the following templates have unique views for each state:
- home page with state selected
- your polling place
- state voting guide

We can start with a demo state for each of these similar to how we did the registration pages, before adding all states.

These pages are singular:
- check your registration
- find your polling place
- no polling place found
- learn about voting

Then translations can be added in, but might be another PR.

cc: @rogeruiz

**Comment by harnettjames** [comment]
It'd be great to get this pull moving again
@jmilcetich and @edgardomoralesGSA

**Comment by jpyuda** [comment]
@jamesharnett we might pick this back up this summer, but I need to run some things down on my end first. New team members ramping on soon.

**Pull request closed without merging**
