### PR TITLE
VOTE-392: homepage accordion

### PR DESCRIPTION
**Pull request by mlloydbixal**
Implements the homepage accordion design in english.

### CODE REVIEW

**Comment by rayestrada** [comment]
@clmedders Can you review the error found in Cypress functional test and determine how we can fix?

**Comment by clmedders** [comment]
> @clmedders Can you review the error found in Cypress functional test and determine how we can fix?

@rayestrada just retook a look and there are multiple links with cypress, you have to tell it which one it has to interact with so it's failing cause it does not know how to interact with the repeated elements... I can update the test and add it to this PR or make a separate one.  I did create a ticket to address this and update the test overall in cypress for the next sprint. I'm good with whatever you prefer!

**Comment by rayestrada** [comment]
@clmedders please create a new branch off this one and modify the test. When it's ready, make a PR against this branch. Since we do not have the final content for the accordions I think it would be safe to add it to the next sprint.

**Comment by rayestrada** [comment]
@mlloydbixal can you resolve the merge conflict?

**Review by rayestrada — APPROVED** [review]
This looks good. I have created a separate task for optimization of the accordion.scss file.

**Review by rayestrada — APPROVED** [review]

**Pull request merged**
